### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by throwaway10** [wothke/websid#3]
Tiny'R'Sid and WebSid were apparently based on TinySid.  The README says "Copyright (C) 1999-2012 T. Hinrichs, R. Sinsch (original licensing applies)"

But what was this original licensing?  Well, originally TinySid was source-available but was not open source.  As of V0.965 which is the most recent I can find ( http://csdb.dk/release/?id=144397 ) the license read: "spreading of the source code is FORBIDDEN!!!"

Unless there is a more recent version with a different license?

According to the comments at https://github.com/wothke/websid/blob/9f02eac79376e149d7f00ee48ecc3be035740390/src/sidengine.c WebSid also incorporated modifications taken from Rockbox: https://github.com/stsquad/rockbox/blob/master/apps/codecs/sid.c

This code was apparently ported to Rockbox by Rainer Sinsch and released under the GPL.

So it sounds as if we have code that can't be shared combined with code that can only be distributed under the GPL?  Which would lead to a project that can't be distributed at all!

If we assume Sinsch is happy to have his code distributed under GPL we further have the problem that it is not being distributed under GPL, but by a CC license that is incompatible with the GPL.

I realise that most of this problematic code has since been replaced, but the GPL is viral and applies to all derivative versions, even if none of the original code remains.  The only way to remove it is either:
    A.  To delete the GPLed files and get them reimplemented by someone who has never looked at the GPLed code in a clean-room implementation.
    B. To ask Hinrichs and Sinsch to re-license their code under CC.

Personally, if you are unable to contact them, I would just assume that Sinsch is happy with GPL and change the license of WebSid to GPL.

(To anyone fact-checking this, note that there is another project called Tinysid, which is a derivative of SIDPlayer, which is a derivative of Frodo.  This project does not seem to be related to Tiny'R'Sid/WebSid/TinySid!)

**Comment by wothke** [comment]
fixed inconsistent "readme" comment. license stays "CC BY-NC-SA" see confirmation by Rainer Sinsch : 

"Hallo Jürgen,

also da machen wir uns mal gar keinen Kopf. Du hast hiermit die Erlaubnis das Teil so einzusetzen, wie Du es für richtig erachtest. Eingenommen der CC BY-NC-SA Lizens.
..
Viele Grüße
Rainer"
