### ISSUE TITLE
Random play

### ISSUE THREAD

**Issue by doyousketch2** [wothke/websid#4]
Cool project.  Wish you could click on an HSVC folder and it would give you the ability to randomly play songs from that folder.

**Comment by wothke** [comment]
I agree that it might be useful to have some feature to play specific folder(s) - without having to manually create a playlist first (or to switch songs manually). Maybe some "add folder to playlist" feature might do the trick.

However I am not convinced that an added "random" functionality would do much good: My "problem" with HVSC is that of the about 50'000 song files, I like only a small fraction of maybe 5%, i.e. 95% of the time a "random play" mode would serve me songs that I'd rather not listen to.. (there may be exceptions, say you'd use that feature on the folder of one of those few composers that consistently have done top notch stuff most of the time..)

**Comment by doyousketch2** [comment]
I agree there's a lot of songs that won't contribute much to one's musical enjoyment.  
However, there's artists who had particularly decent skill when creating compositions on the Commodore.  Clicking a dir and randomly hearing a random selection of songs made by that individual would be enjoyable.

**Comment by wothke** [comment]
Just added 2 features which should make your life easier on the "Explorer" page: 

1. There is now a "shuffle" mode which can be toggled via the new symbol on the righthand side of the "stop" button. It affects whatever is played from the currently used playlist.
2. A new right-click context menu for the HVSC tree view provides an "add to playlist" option: The context menu is available exclusively for folders that directly contain SID files and the folder must have been expanded prior to using the context menu (the tree structure is always loaded on demand and unless a folder has already been opened the context menu does not know what might be inside). Based on the sid-files directly contained in the folder, the functionality creates playlist entries for all available tracks which have a playtime of at least 20secs (filtering out typical game sound effects).

(also see https://www.facebook.com/TinyRSid/posts/1748535501844720)
