### ISSUE TITLE
.str support

### ISSUE THREAD

**Issue by Sgeo** [wothke/websid#6]
Would it be possible to support .mus/.str files? (.str files are just mus files that are played on a second SID chip while the .mus is played on the first chip)

**Comment by wothke** [comment]
The emulator already uses "Enhanced Sidplayer" by Craig Chamberlain (see CGSC/00_Commodore64/MusicSys.d64/SID PLAYER.64) and it already does play individual 
.mus/.str files (see https://deepsid.chordian.net/?file=/Compute%27s%20Gazette%20SID%20Collection/).
However it only supports single SID mode, i.e. it will NOT look for a potentially existing, separate .str file. 
Technically it would obviously be possible to implement respective multi-SID support (i.e. replace the Sidplayer and add "load on demand") but I have no plans to do that.
